version: '3.8'

services:
  emqx:
    environment:
      - "EMQX_NAME=myemqx"
      - "EMQX_HOST=127.0.0.1"
      - "EMQX_NODE__cookie=s0m3r4nd0mt3xt"
      - "EMQX_DASHBOARD__DEFAULT_PASSWORD=${LYRICS_EMQX_DASHBOARD_PASSWORD}"
      - "EMQX_LISTENERS__TCP__DEFAULT__enabled=false"
      - "EMQX_LISTENERS__WS__DEFAULT__enabled=false"
      - "EMQX_AUTHENTICATION__1__backend=built_in_database"
      - "EMQX_AUTHENTICATION__1__mechanism=password_based"
      - "EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__cacertfile=$${EMQX_ETC_DIR}/isrgrootx1.pem"
      - "EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__certfile=$${EMQX_ETC_DIR}/certs/${LYRICS_HOSTNAME}.crt"
      - "EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__keyfile=$${EMQX_ETC_DIR}/certs/${LYRICS_HOSTNAME}.key"
      - "EMQX_LISTENERS__WSS__DEFAULT__SSL_OPTIONS__cacertfile=$${EMQX_ETC_DIR}/isrgrootx1.pem"
      - "EMQX_LISTENERS__WSS__DEFAULT__SSL_OPTIONS__certfile=$${EMQX_ETC_DIR}/certs/${LYRICS_HOSTNAME}.crt"
      - "EMQX_LISTENERS__WSS__DEFAULT__SSL_OPTIONS__keyfile=$${EMQX_ETC_DIR}/certs/${LYRICS_HOSTNAME}.key"

    volumes:
      - ./emqx-data:/opt/emqx/data
      - ./emqx-log:/opt/emqx/log
      - ./emqx-conf/isrgrootx1.pem:/opt/emqx/etc/isrgrootx1.pem
      - ./emqx-conf/acl.conf:/opt/emqx/etc/acl.conf
      - ./caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/${LYRICS_HOSTNAME}/:/opt/emqx/etc/certs:ro
