version: '3.8'

services:
  nats:
    image: nats:alpine
    pull_policy: always
    ports:
      - "8443:8443"
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats-conf/nats-server.conf:/etc/nats/nats-server.conf
      - ./nats-data:/data/jetstream
      - ./caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/${LYRICS_HOSTNAME}/:/data/tls:ro
    depends_on:
      - caddy
    restart: unless-stopped    

  caddy:
    image: caddy:latest
    pull_policy: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "LYRICS_HOSTNAME=${LYRICS_HOSTNAME}"
    volumes:
      - ./caddy-data:/data
      - ./caddy-conf/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy-wwwroot:/wwwroot
    restart: unless-stopped

  emqx:
    image: emqx/emqx:5.4.1
    pull_policy: always
    ports:
      - "8883:8883"   # MQTT over TLS
      - "8084:8084"   # WSS over TLS
      - "18083:18083" # Admin Web Interface
    # env and volumes, see override
    depends_on:
      - caddy
    restart: unless-stopped    
